---
title: "proyecto"
author: "Lidia y Andrés"
date: "21/09/2022"
output: "word_document"
---
#packages for modelling and visualization
```{r}
library(MuMIn)
library(DHARMa)
library(ggplot2)
library(mgcv) 
library(tidymv) 
library(visreg) 
library(mgcViz) 
library(dplyr)
library(here)
library(readr)

```

Subir datos de DIVERSIFICA:

```{r read_data, include=FALSE}

DIVERSIFICA.plot <- read_delim(here("data/st.DIVERSIFICA.plot.csv"), delim = ";")
DIVERSIFICA.plot <- DIVERSIFICA.plot[-27, ]
DIVERSIFICA.plot$DBH2 <- DIVERSIFICA.plot$DBH^2

DIVERSIFICA.tree <- read_delim(here("data/st.DIVERSIFICA.tree.strange.csv"), delim = ";")
```

```{r gam}
gam <- gam(def ~ s(DBH) + s(mycrhz) + s(NO3) + s(comp), data = DIVERSIFICA.plot)
```
```{r}
gam <- gam(def ~ s(DBH), data = DIVERSIFICA.plot)
visreg(gam)
```

```{r}
gam <- gam(def ~ s(mycrhz), data = DIVERSIFICA.plot)
visreg(gam)
```

```{r}
gam <- gam(def ~ s(comp), data = DIVERSIFICA.plot)
visreg(gam)
```

```{r}
gam <- gam(def ~ s(NO3), data = DIVERSIFICA.plot)
visreg(gam)
```


```{r Linear Model, echo=FALSE}

plotModel<- lm (def ~ DBH + DBH2 + mycrhz + NO3 + comp, data = DIVERSIFICA.plot, na.action = na.fail)

#to compare all possible models with AIC
res <- dredge(plotModel, trace=0)

```

Keep only the best models and visualize them:

```{r subset, echo = TRUE}
subset(res, delta <= 2)

```

See the error of the estimate and the significance of the effect

```{r summary, echo = TRUE}

summary(model.avg(res, subset = delta < 2, revised.var=FALSE))

```

See the importance of each variable:

```{r importance, echo = TRUE}

sw(subset(model.sel(res), delta <= 2))

```

<<<<<<< HEAD

```{r dharma, echo = TRUE}

simulateResiduals(plotModel, plot = TRUE)

```

Plot model visreg

```{r plotting, echo = TRUE}
visreg(plotModel)
```
```{r}
visreg(plotModel, gg=T) + geom_smooth(formula = lm(def ~ DBH + DBH2 + comp + mycrhz), data = DIVERSIFICA.plot)

#cogido de internet cambiando el nombre de las variables (la secuencia de valores de DBH no tiene sentido, le pongo numeros con sentido)
DBHvalues <- seq(0, 30, 0.1)
predicteddef <- predict(plotModel,list(DBH=DBHvalues, DBH2=DBHvalues^2))
plot(DBH, def, pch=16, xlab = "DBH (cm)", ylab = "Defoliation (%)", cex.lab = 1.3, col = "blue")
lines(DBHvalues, predicteddef, col = "darkgreen", lwd = 3)

#probando a cambiar la secuencia por el vector de DBH
DBHvalues <- seq(-1.305547, 1.786487, 0.01)
predicteddef <- predict(plotModel)
plot(DIVERSIFICA.plot$DBH, DIVERSIFICA.plot$def, pch=16, xlab = "DBH (cm)", ylab = "Defoliation (%)", cex.lab = 1.3, col = "blue")
lines(DBHvalues, predicteddef, col = "darkgreen", lwd = 3)

range(DIVERSIFICA.plot$DBH)
```

-   
